version: '3.4'
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      args:
        requirements: requirements.local.txt
    ports:
      - "${PORT_BACKEND}:8000"
    environment:
      - TIME_ZONE=Europe/Madrid
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    links:
      - postgres

  postgres:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    name: database_data