# Generated by Django 2.1.7 on 2019-03-16 13:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('guid', models.CharField(blank=True, db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('author', models.CharField(blank=True, max_length=255)),
                ('duration', models.DurationField(blank=True, help_text='The episode duration in hours, minutes, and seconds.', null=True)),
                ('image_url', models.URLField(blank=True, help_text='Artwork must be a minimum size of 1400 x 1400 pixels and a maximum size of 3000 x 3000 pixels, in JPEG or PNG format, 72 dpi, with appropriate file extensions (.jpg, .png), and in the RGB colorspace.', max_length=500)),
                ('season', models.PositiveIntegerField(blank=True, help_text='The episode season number.', null=True)),
                ('episode', models.PositiveIntegerField(blank=True, help_text='The episode season number.', null=True)),
                ('pub_date', models.DateTimeField(db_index=True)),
                ('stream_url', models.URLField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PodcastShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, help_text='Describe subject matter, media format, episode schedule and other relevant information while incorporating keywords.')),
                ('language', models.CharField(blank=True, help_text='See <a href="http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes">ISO 639-1</a> and <a href="http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements">ISO 3166-1</a> for more language codes.', max_length=7)),
                ('image_url', models.URLField(blank=True, help_text='Artwork must be a minimum size of 1400 x 1400 pixels and a maximum size of 3000 x 3000 pixels, in JPEG or PNG format, 72 dpi, with appropriate file extensions (.jpg, .png), and in the RGB colorspace.', max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('url', models.URLField(help_text='URL of a Podcast RSS feed to ingest', max_length=255, unique=True)),
                ('is_valid', models.BooleanField(default=False, help_text='Indicates if the feed has been successfully parsed.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='podcastshow',
            name='rss_feed',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='show', to='podcasts.RSSFeed'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcasts.PodcastShow'),
        ),
    ]
